site_name: Extrator NFS-e
site_url: https://rafaeldatamaster.github.io/scrapper_nfe/
repo_url: https://github.com/rafaeldatamaster/scrapper_nfe
repo_name: Scrapper NFe

# Configuração do Tema Sóbrio (Material Design)
theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs          # Abas no topo (estilo moderno)
    - navigation.sections      # Seções expansíveis no menu
    - toc.integrate            # Índice integrado na lateral esquerda (limpo)
    - content.code.copy        # Botão de copiar nos blocos de código
  palette:
    # Esquema Claro (Profissional/Corporativo)
    - scheme: default
      primary: white           # Barra superior branca (muito elegante)
      accent: indigo           # Detalhes sutis em azul índigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro

    # Esquema Escuro (Opcional - bom deixar disponível)
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

# Plugins para funcionalidades extras
plugins:
  - search                     # Barra de busca
  - mkdocstrings              # Documentação automática de código
  - encryptcontent:           # Proteção por senha
      title_text: "Acesso Restrito - Master"
      placeholder_text: "Digite a senha do projeto"
      password: "M4sterKey@0912"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Estrutura do Menu (Navegação)
nav:
  - Visão Geral: index.md
  - Arquitetura:
      - Design e Padrões: arquitetura.md
      - Decisões Técnicas: insights.md
  - Funções: api.md